config/routes.rb
Rails.application.routes.draw do
  get 'users/:id' => 'users#show', as: :user

  resources :items
  resources :shopping_lists
  resources :stores
  devise_for :users
  root 'pages#index'
  put "toggleadmin/:id" => 'pages#toggleadmin', :as => "toggleadmin"
  put "toggleapproved/:id" => 'pages#toggleapproved', :as => "toggleapproved"
  PagesController.action_methods.each do |action|
      get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shopping_lists
  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <% if current_user.admin? %>
      <div class="col-md-6 user-profile">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
            <h3><%= @user.name %></h3>
            </div>
            <div class="card-text">
              <p>Email: <%= @user.email %></p>
            <% if @user.admin? %>
              <%= button_to "Remove Admin", toggleadmin_url, method: :put, class:"btn btn-danger" %>
            <% else %>
              <%= button_to "Add Admin", toggleadmin_url, method: :put, class:"btn btn-success" %>
            <% end %>
            <% if @user.approved? %>
              <%= button_to "Remove Approved", toggleapproved_url, method: :put, class:"btn btn-danger" %>
            <% else %>
              <%= button_to "Add Approved", toggleapproved_url, method: :put, class:"btn btn-success" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-md-6 user-profile">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
              <h3><%= @user.name %></h3>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>