config/routes.rb
Rails.application.routes.draw do
  get 'users/:id' => 'users#show', as: :user

  resources :items
  resources :shopping_lists
  resources :stores
  devise_for :users
  root 'pages#index'
  put "toggleadmin/:id" => 'pages#toggleadmin', :as => "toggleadmin"
  put "toggleapproved/:id" => 'pages#toggleapproved', :as => "toggleapproved"
  PagesController.action_methods.each do |action|
      get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :store
  belongs_to :user
  has_many :shopping_list_items
  validates :date, presence: true
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /shopping_lists
  # GET /shopping_lists.json
  def index
    @shopping_lists = ShoppingList.all
  end

  # GET /shopping_lists/1
  # GET /shopping_lists/1.json
  def show
    @items = Item.where(store: @shopping_list.store)
  end

  # GET /shopping_lists/new
  def new
    if current_user && current_user.admin?
      @shopping_list = ShoppingList.new
      @stores = Store.all
    else
      redirect_to shopping_lists_path, notice: "Permissions are required to add shopping lists"
    end

  end

  # GET /shopping_lists/1/edit
  def edit
    @stores = Store.all
  end

  # POST /shopping_lists
  # POST /shopping_lists.json
  def create
    @shopping_list = ShoppingList.new(shopping_list_params)
    @shopping_list.user_id = current_user.id
    respond_to do |format|
      if @shopping_list.save
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list }
      else
        format.html { render :new }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_lists/1
  # PATCH/PUT /shopping_lists/1.json
  def update
    respond_to do |format|
      if @shopping_list.update(shopping_list_params)
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_list }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_lists/1
  # DELETE /shopping_lists/1.json
  def destroy
    @shopping_list.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list
      @shopping_list = ShoppingList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_params
      params.require(:shopping_list).permit(:store_id, :user_id, :date, :time)
    end
end

app/views/shopping_lists/_form.html.erb
<%= form_with(model: shopping_list, local: true) do |form| %>
  <% if shopping_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_list.errors.count, "error") %> prohibited this shopping_list from being saved:</h2>

      <ul>
      <% shopping_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @shopping_list.store_id.nil? %>
  <div class="field">
    <%= form.label :store_id %>
    <%= form.collection_select(:store_id, @stores, :id, :name) %>
  </div>
  <% else %>
    <h4>Editing Shopping List for <%= @shopping_list.store.name %></h4>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :shopping_list_date %>
  </div>
  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :shopping_list_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_lists/edit.html.erb
<%= render 'form', shopping_list: @shopping_list %>

<%= link_to 'Show', @shopping_list %> |
<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Lists</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>User</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_lists.each do |shopping_list| %>
      <tr>
        <td><%= shopping_list.store.name %></td>
        <td><%= shopping_list.user.email %></td>
        <td><%= shopping_list.date %></td>
        <td><%= shopping_list.time %></td>
        <td><%= link_to 'Show', shopping_list %></td>
        <% if current_user && current_user.approved?  %>
        <td><%= link_to 'Edit', edit_shopping_list_path(shopping_list) %></td>
        <td><%= link_to 'Destroy', shopping_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Shopping List', new_shopping_list_path, class: "btn btn-info btn-sm active" %>

app/views/shopping_lists/new.html.erb
<h1>New Shopping List</h1>

<%= render 'form', shopping_list: @shopping_list %>

<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h3 class="text-center"><%= @shopping_list.store.name %></h3>
  <div>
    <strong>Shopper:</strong>
    <%= @shopping_list.user.name %>
  </div>

  <div>
    <strong>On:</strong>
    <%= @shopping_list.date.strftime("%m/%d/%y") %>
    <strong>at</strong>
    <%= @shopping_list.time.strftime("%H:%M %p") %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Item</th>
        <th>Category</th>
        <th>Price</th>
        <th>Sale</th>
        <th>Add to List</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.category %></td>
        <td>$<%= item.regularprice %></td>
        <td>$<%= item.saleprice %></td>
        <td>Add</td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <ul>
  </ul>

  <div class="show-nav">
    <%= link_to 'Edit', edit_shopping_list_path(@shopping_list) %> |
    <%= link_to 'Back', shopping_lists_path %>
  </div>
</div>